Add bookings
GlebInside/java-shareit pull request #2
Opened 2022-07-30 12:50 UTC by GlebInside

2022-08-01 07:20 UTC, kukolev requested changes

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +//        model.setApproved(dto.getStatus() == Status.APPROVED);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +/**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +//        else if (model.getCanceled()) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +        try {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .filter(Booking::getApproved)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .filter(Booking::getApproved)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .sorted((a,b)->Integer.compare(b.getId(),a.getId()))
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +                //.map(b->BookingMapper.toDto(b, itemMapper))
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +    private final UserRepository userRepository;
По условиям ТЗ контроллеры должны зависеть только от сервисов. Хранилища должны быть внедрены в сервисы. Это позволяет логически отделить слой API от слоя бизнес-логики.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +        var item = itemService.getById(id);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +        try {
Для обработки исключений лучше использовать @ExceptionHandler, а не обрабатывать вручную. Этот подход фактически является стандартом в разработке.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/item/model/Comment.java
> +    int id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/requests/dto/ItemRequestDto.java
> +    String description;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-01 09:07 UTC, GlebInside commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +//        model.setApproved(dto.getStatus() == Status.APPROVED);
Исправлено

2022-08-01 09:07 UTC, GlebInside commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +/**
Исправлено

2022-08-01 09:08 UTC, GlebInside commented on src/main/java/ru/practicum/booking/BookingMapper.java
> +//        else if (model.getCanceled()) {
Исправлено

2022-08-01 09:08 UTC, GlebInside commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .filter(Booking::getApproved)
Исправлено

2022-08-01 09:08 UTC, GlebInside commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .filter(Booking::getApproved)
Исправлено

2022-08-01 09:08 UTC, GlebInside commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +//                .sorted((a,b)->Integer.compare(b.getId(),a.getId()))
Исправлено

2022-08-01 09:08 UTC, GlebInside commented on src/main/java/ru/practicum/booking/service/BookingService.java
> +                //.map(b->BookingMapper.toDto(b, itemMapper))
Исправлено

2022-08-01 09:09 UTC, GlebInside commented on src/main/java/ru/practicum/item/model/Comment.java
> +    int id;
Исправлено

2022-08-01 09:09 UTC, GlebInside commented on src/main/java/ru/practicum/requests/dto/ItemRequestDto.java
> +    String description;
Исправлено

2022-08-02 08:48 UTC, GlebInside commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +        try {
Исправлено

2022-08-02 08:48 UTC, GlebInside commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +    private final UserRepository userRepository;
Исправлено

2022-08-02 08:48 UTC, GlebInside commented on src/main/java/ru/practicum/item/controller/ItemController.java
> +        var item = itemService.getById(id);
Исправлено

2022-08-02 08:54 UTC, GlebInside commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +        try {
Исправлено

2022-08-03 07:48 UTC, kukolev requested changes

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +            try {
Здесь происходит задержка потока на 1 секунду и выброс исключения. Это бизнес логика, которой не место в контроллере. Также эта логика не предусмотрена ТЗ. По моему это лишнее и это нужно удалить.

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +            try {
Здесь происходит задержка потока на 1 секунду и выброс исключения. Это бизнес логика, которой не место в контроллере. Также эта логика не предусмотрена ТЗ. По моему это лишнее и это нужно удалить.

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/item/storage/InMemoryItemStorage.java
> +//package ru.practicum.item.storage;
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/user/controller/UserController.java
> +        var u = UserMapper.toUser(user);
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/item/service/CommentsService.java
> +    public CommentsService(CommentsRepository commentsRepository, UserRepository userRepository, BookingService bookingService) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-03 07:48 UTC, kukolev commented on src/main/java/ru/practicum/item/service/CommentsService.java
> +        var bookings = bookingService.getAllStartedByBookerAndItem(model.getAuthor().getId(), model.getItem().getId(), true, false);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-03 09:25 UTC, GlebInside commented on src/main/java/ru/practicum/item/service/CommentsService.java
> +    public CommentsService(CommentsRepository commentsRepository, UserRepository userRepository, BookingService bookingService) {
Исправлено

2022-08-03 09:25 UTC, GlebInside commented on src/main/java/ru/practicum/item/service/CommentsService.java
> +        var bookings = bookingService.getAllStartedByBookerAndItem(model.getAuthor().getId(), model.getItem().getId(), true, false);
Исправлено

2022-08-03 09:25 UTC, GlebInside commented on src/main/java/ru/practicum/user/controller/UserController.java
> +        var u = UserMapper.toUser(user);
Исправлено

2022-08-03 09:26 UTC, GlebInside commented on src/main/java/ru/practicum/item/storage/InMemoryItemStorage.java
> +//package ru.practicum.item.storage;
Исправлено

2022-08-03 10:16 UTC, GlebInside commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +            try {
Исправлено. Тесты работают некорректно без задержки.

2022-08-03 10:16 UTC, GlebInside commented on src/main/java/ru/practicum/booking/controller/BookingController.java
> +            try {
Исправлено. Тесты работают некорректно без задержки.

2022-08-03 17:06 UTC, kukolev requested changes

2022-08-03 17:06 UTC, kukolev commented on .github/workflows/api-tests.yml
> +          /tmp/wait-for-it.sh -t 1200 localhost:8080
Если тесты не проходят из-за того, что код работает долго, то это скорее всего проблема в коде. Нужно искать и исправлять ошибку, а не править тест.

2022-08-05 15:02 UTC, merged